### ISSUE TITLE
Phone calls

### ISSUE THREAD

**Issue by yosisah** [gartnera/headunit#39] opened 2017-01-10 18:05 UTC
First of all I want to say thank you for the amazing project.

My problem is when I connected with my phone and I received a call, it's stuck and I don't hear the call not from the Bluetooth and not from my phone, it's look like the Bluetooth trying to connect to the Mazda connect, and in the same time trying to connect to the Android auto .
I found that I need to disconnect my phone from the USB and the Bluetooth just to get it work again with the phone speaker , please help .

Phone : Nexus 6P Android 6.0.1
Android auto: 0.94 latest 
Car: Mazda 3 2016

**Comment by izacus** [comment] 2017-01-20 07:29
Duplicate of #2.

**Closed** 2017-02-01 07:28 UTC
Labels: duplicate
