### ISSUE TITLE
Night Maps wird behaviour

### ISSUE THREAD

**Issue by felipecorrea9** [gartnera/headunit#40] opened 2017-01-12 03:32 UTC
Hi, 
For some reason maps are not working with its night version. A wird thing happened. 
It was 19.00, when I was driving and suddenly maps change to its night version. Here at 19.00 hrs we still have light.
Anyway, I use the GPS again at 22.20 pm (its dark at that time) and maps didnt change to night version.

Is there a fix for this?

Regards,

**Comment by izacus** [comment] 2017-01-12 09:39
Uhh... the new version synchronizes night mode with the cars nightmode (and auto lights if your car is equipped with them). Use the dashboard dimmer button to switch your dashboard to nightmode or not.

**Comment by felipecorrea9** [comment] 2017-01-12 12:29
that is version 0.94? Or should I download the latest comited version?

Thanks!

Regards,

**Comment by izacus** [comment] 2017-01-12 12:45
That's the latest version. 0.94 has nightmode hardcoded for 7am/pm or something.

**Comment by felipecorrea9** [comment] 2017-01-12 13:50
RIght but, It looks that it changes only when the clock changes to 7/pm, but if I turn on the car at 10 pm, it shows me the day map only.

**Comment by izacus** [comment] 2017-01-12 14:10
Yes, it's buggy. You can override that inside Android Auto developer settings on your phone - set it to "Phone controlled" and it should be better.

**Comment by felipecorrea9** [comment] 2017-01-12 14:15
Where can I find the developer settings on my phone?

Thanks!

**Comment by viktorgino** [comment] 2017-01-12 15:12
A potential solution could be calculating sunset/rise times using geolocation: http://stackoverflow.com/q/7064531/4789943

**Comment by viktorgino** [comment] 2017-01-12 15:20
@fellipecorrera9
From https://developer.android.com/training/auto/testing/index.html#phone :

> 1. In the Android Auto app, tap the Hamburger menu.
> 2. Tap About.
> 3. Tap About Android Auto header 10 times, until a toast appears thar says "Developer mode enabled".
> 4. Now you can access developer mode by selecting the overflow menu dots on the top right of the handheld screen.

**Comment by borconi** [comment] 2017-01-16 23:17
@izacus - Take this https://gist.github.com/Tafkas/4742250 and port it to C
In Android I'm pulling a new GPS location each 10 minutes and update the values, in case you are driving north or south a lot the values will change, so you want to keep it up to date. I think you can achieve the same in C.

**Comment by izacus** [comment] 2017-01-20 07:29
Having nightmode synchronized with the rest of the car is working as intended (it's the same as the rest of CMU, dashboard, lights and built-in navigation does). Anyone that wants to have that synchronized with the time can always override it in AA and set the night-mode as phone controlled.

**Comment by ryoncy** [comment] 2017-01-20 07:46
@izacus i already change to "phone-controlled" night mode in AA app settings but still showing day mode when i using at night 10:45PM, please advise other solution....

**Comment by izacus** [comment] 2017-01-20 08:54
Again, if you're using 0.94 then you don't have the fix yet.

**Comment by ryoncy** [comment] 2017-01-20 10:50
@izacus what is the fix ?

**Comment by mishaaq** [comment] 2017-02-01 09:31
This has been fixed in master branch already. I've tested it yesterday and is working as intended (night mode turns on with headlights). I think this issue may be closed as resolved.

**Comment by ryoncy** [comment] 2017-02-02 14:04
@mishaaq i download latest master branch try can't start AA. which version you using ?
can you share with us the installer file.

**Comment by mishaaq** [comment] 2017-02-02 15:03
@ryoncy I installed current master. Did you compiled it or only copied the "installer" directory from ./mazda?
@lmagder what about releasing new version?

**Comment by ryoncy** [comment] 2017-02-03 00:59
@mishaaq i uninstall V0.94 by izacus then install the installer" directory from ./mazda

so i need compiled two together then install?

**Comment by lmagder** [comment] 2017-02-03 05:11
@mishaaq I'm thinking about it, but I want the code to "rest" a bit since I made so many huge refactors recently. Brave people like you seem to be trying it building themselves so via that I want to make sure stuff is stable and works on cars other than mine before confusing lots of less technical people and possibly bricking cars :)

**Comment by mishaaq** [comment] 2017-02-03 10:50
@lmagder AFAIK the bricking possibilities passed away with removing input-filter and messing with sm.conf or I've missed something and my bravery comes from unfamiliarity :D?
@ryoncy I've uploaded archive with AA I'm currently using to mega http://www.megafileupload.com/cxO8/AA_master.zip. Use it at your own risk!

**Comment by ryoncy** [comment] 2017-02-03 12:16
@mishaaq Thanks.

**Comment by mishaaq** [comment] 2017-02-03 14:18
Commit 290ccbff1b7b2ddb9c2817b3734da95ed4d6bcc1 fixes #40

**Comment by ryoncy** [comment] 2017-02-04 11:33
@mishaaq i installed your AA_master version all working great, thanks a lot for your help and sharing.
@felipecorrea9 i think this issue is solved can close it.

**Comment by izacus** [comment] 2017-02-08 15:24
Yup, solved on master.

**Closed by izacus** 2017-02-08 15:24 UTC
