### ISSUE TITLE
when AA is installed, it is not currently possible to make a phone call at all, even if the phone is not connected to USB.

### ISSUE THREAD

**Issue by Jinmcx** [gartnera/headunit#53] opened 2017-02-14 16:34 UTC
Back in .93 return to mzd (on AA option) actually kills AA but it seems to be persistent in the new version there's no way to get rid of it. Typically I kill AA to make a phone call but seems not possible atm.

**Comment by bdr99** [comment] 2017-02-15 16:45
Just to add to this, it seems like if AA is installed, it is not currently possible to make a phone call at all, even if the phone is not connected to USB.

**Comment by mishaaq** [comment] 2017-02-18 11:49
@bdr99 confirmed

**Comment by lmagder** [comment] 2017-02-18 20:37
AA is persistent in the new design since that's how real AA headunits work. If you've noticed with 0.94 the phone displays a "your car software has crashed" message when AA quits since the only time the connection is supposed to be interrupted is when USB disconnects since the phone can have neither audio or video focus.

Which commit are you guys testing with? After merging @izacus 's BT service stuff I can actually make a call via AA, just the audio goes through the phone and the input is still captured so you can't use the UI, but we are getting closer 😃 

That said, i would kind of expect the phone support to be messed up more now since the protocol is always kept alive when connected via USB so the phone thinks it can do call stuff through AA and probably sends messages which our code doesn't handle correctly.

However I'm really surprised there is any difference in calling when not connected via USB since in that situation the HU software is totally asleep, waiting on a usb hotplug event.

I have seen cases where once the phone connects through AA it stops automatically connecting to the car via BT since it's waiting for the AA message to connect (which never comes in our code). To fix this I went into the BT menu on my phone and clicked the car. They were still paired, just not auto-connecting. Are you guys sure you are not hitting this case?

I'm going to rename this to "when AA is installed, it is not currently possible to make a phone call at all, even if the phone is not connected to USB." since Returning to MZD not killing AA is by design and should not be necessary

**Comment by mishaaq** [comment] 2017-02-20 08:30
Having a version just before merged @izacus BT stuff I've noticed that I can't make a call using "native" way - CMU was dropping a connection with info about using a phone. Therefore I've disconnected the phone from USB and tried once again with the same result.
So, maybe it will work after fresh start of the infotainment system, but it looks like something is not cleaned up when disconnecting the phone.

**Comment by Jinmcx** [comment] 2017-02-20 14:34
That make sense but I mainly reported this because I wanted a way to make phone calls but if phone call works then there's absolutely no reason to kill AA :]!

**Comment by Jinmcx** [comment] 2017-02-22 20:40
@lmagder You okay? I heard about the flood :[. SoCal is good.. you gonna move down to where it's safe.

**Comment by ryoncy** [comment] 2017-02-24 14:27
@lmagder @mishaaq @Jinmcx  i also facing problem in call, after install AA even not using AA when make a call and pickup call it will transfer call to handphone.

**Comment by pzawadzki82** [comment] 2017-03-23 19:14
I have MZD Connect 56.00.513 EU N and after installing Android Auto (using AIO Tweaks 2.5.0) I cannot make phone calls using car speaker. When number is dialled I'm automatically redirected to my phone (with message "Call on handset"). When I press button "Transfer to vehicle" its trying but after 1-2s my call is redirected to phone speaker. After uninstalling Android Auto bluetooth calls working fine.

**Comment by cobhc999** [comment] 2017-04-11 07:49
Is there a workaround for this problem? For example using tasker when there's an incoming call deactivate bluetooth and AA so i can take the call with the phone itself?

**Comment by pzawadzki82** [comment] 2017-04-11 08:18
I haven't found workaround:( Just uninstalled Andoird Auto and wait for fix

**Comment by izacus** [comment] 2017-04-25 09:07
No, but preventing AA from running in background all the time (as it did before) would probably mitigate the issue - you'd be able to call if AA isn't running.

**Comment by y2jhotaru** [comment] 2017-05-16 16:05
@lmagder I'm facing the same issue with 56.00.513A N

**Comment by Scorcher7986** [comment] 2017-08-14 00:51
Is there any easy way to modify the current build to prevent AA from running in background (requiring it to be opened in the app menu), or would I have to use the older 0.9x build?

**Comment by Trevelopment** [comment] 2017-09-02 20:49
Fixed #78

**Comment by lmagder** [comment] 2017-09-09 23:35
Yup should be fixed in TOT now

**Closed by lmagder** 2017-09-09 23:35 UTC
Labels: bug, phone call support

**Comment by marcinjakubowski** [comment] 2017-09-14 10:30
Sorry if this is not the right place, but any idea when this lands in AIO? I think a lot of people are waiting for it, I know I certainly am. @Trevelopment?

**Comment by y2jhotaru** [comment] 2017-09-14 21:30
@Trevelopment So far the fix in the call issue has worked like a charm. If you've fixed the focus issue, you're my hero. Thanks a lot

**Comment by Trevelopment** [comment] 2017-09-14 23:41
@y2jhotaru #80
